events {
    worker_connections 1024;
}

http {
    # Redirigir todo el tráfico HTTP (80) a HTTPS (443)
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # Servidor seguro HTTPS
    server {
        listen 443 ssl;
        server_name localhost;

        # Rutas a los certificados que generamos
        ssl_certificate /etc/nginx/certs/grafana.crt;
        ssl_certificate_key /etc/nginx/certs/grafana.key;

        # Configuraciones de seguridad recomendadas
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            # Apuntar al contenedor de Grafana en la red interna de Docker
            proxy_pass http://grafana:3000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}